stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  tags:
    - test

  stage: build

  script:
    - echo "build dockerfile..."
    - docker container ls -a
    - docker build -t 0.0.0.0:8000/users:v1.0 -f Dockerfile.userapp .
    - docker push 0.0.0.0:8000/users:v1.0
    - docker build -t 0.0.0.0:8000/movies:v1.0 -f Dockerfile.moviesapp .
    - docker push 0.0.0.0:8000/movies:v1.0
    - docker images
    - echo "build complete."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - test
	environment: production
  script:
    - echo "Deploying application image..."
    - minikube image load 0.0.0.0:8000/users:v1.0
    - minikube image load 0.0.0.0:8000/movies:v1.0
    - echo "Application image successfully deployed."
